Repository kinvolk/lokomotive, pull requests merged in 2020-11, with the labels that each got.

#1190 Fix GitHub actions
  .github/workflows/ci.yaml
  Makefile
Labels: priority/P1

#1186 pkg/platform/packet: improve hardware reservations validation rules
  docs/configuration-reference/platforms/packet.md
  pkg/platform/packet/packet.go
  pkg/platform/packet/packet_test.go
Labels: priority/P2

#1163 docs: OpenEBS upgrade guide.
  docs/how-to-guides/upgrade-openebs.md
Labels: kind/documentation, priority/P3

#1151 .github/workflows/ci.yaml: update golangci-lint to v1.33.0
  .github/workflows/ci.yaml
  Makefile
Labels: priority/P3
