Repository kinvolk/lokomotive, pull requests merged in 2020-09, with the labels that each got.

#907 packet: ignore changes to plan and user_data on controller nodes
  assets/terraform-modules/packet/flatcar-linux/kubernetes/controllers.tf
  assets/terraform-modules/packet/flatcar-linux/kubernetes/workers/workers.tf
  docs/configuration-reference/platforms/packet.md
  pkg/assets/generated_assets.go
Labels: size/s

#895 KEYS: Add surajssd gpg key fingerprint
  docs/KEYS.md
Labels: size/s

#909 cli/cmd: fix re-installing controlplane components in custom namespaces
  cli/cmd/cluster.go
Labels: size/s

#901 Makefile: Don't build before linting
  Makefile
Labels: size/s

#951 Remove pkg/install package and improve pkg/lokomotive a bit
  cli/cmd/cluster-apply.go
  pkg/install/install.go
  pkg/install/verify.go
  pkg/lokomotive/cluster.go
Labels: kind/cleanup

#952 Remove pkg/util package
  pkg/config/config.go
  pkg/lokomotive/cluster.go
  pkg/util/path.go
  pkg/util/retryutil/retryutil.go
  pkg/util/tools/tools.go
  test/ingress/aws/aws_test.go
Labels: kind/cleanup

#881 Update Velero component for Packet [openebs and restic plugin support]
  docs/configuration-reference/components/velero.md
  internal/util.go
  internal/util_test.go
  pkg/components/gangway/component.go
  pkg/components/linkerd/component.go
  pkg/components/linkerd/component_test.go
  pkg/components/velero/azure/azure.go
  pkg/components/velero/azure/template.go
  pkg/components/velero/component.go
  pkg/components/velero/component_test.go
  pkg/components/velero/openebs/openebs.go
  pkg/components/velero/openebs/template.go
  pkg/components/velero/restic/restic.go
  pkg/components/velero/restic/template.go
  pkg/components/velero/velero_test.go
Labels: size/l
