Repository kinvolk/lokomotive, pull requests merged in 2020-12, with the labels that each got.

#1181 Fix adding worker pools with TLS bootstrap
  cli/cmd/cluster-apply.go
  cli/cmd/cluster/apply.go
  cli/cmd/cluster/cluster.go
  cli/cmd/cluster/component-apply.go
  cli/cmd/cluster/component-delete.go
  cli/cmd/cluster/health.go
  cli/cmd/cluster/utils.go
  docs/cli/lokoctl_cluster_apply.md
  docs/troubleshooting/_index.md
  docs/troubleshooting/recovering-from-removed-controlplane-chart-release-with-removed-assets-directory.md
  pkg/platform/aws/aws.go
  pkg/platform/baremetal/baremetal.go
  pkg/platform/packet/packet.go
  pkg/platform/platform.go
  pkg/platform/platform_test.go
Labels: priority/P2

#1165 docs: Rook Ceph Upgrade
  docs/how-to-guides/upgrade-rook-ceph.md
Labels: kind/documentation, priority/P3

#1147 Don't use globals for platforms and components registration
  cli/cmd/cluster/cluster.go
  cli/cmd/cluster/component-delete.go
  cli/cmd/cluster/component-render-manifest.go
  cli/cmd/cluster/component.go
  cli/cmd/cluster/utils.go
  pkg/backend/backend.go
  pkg/backend/local/local.go
  pkg/backend/s3/s3.go
  pkg/components/aws-ebs-csi-driver/component.go
  pkg/components/aws-ebs-csi-driver/component_test.go
  pkg/components/cert-manager/component.go
  pkg/components/cluster-autoscaler/component.go
  pkg/components/cluster-autoscaler/component_test.go
  pkg/components/components.go
  pkg/components/contour/component.go
  pkg/components/contour/component_test.go
  pkg/components/dex/component.go
  pkg/components/dex/component_test.go
  pkg/components/external-dns/component.go
  pkg/components/external-dns/component_test.go
  pkg/components/flatcar-linux-update-operator/component.go
  pkg/components/flatcar-linux-update-operator/component_test.go
  pkg/components/gangway/component.go
  pkg/components/gangway/component_test.go
  pkg/components/httpbin/component.go
  pkg/components/httpbin/component_test.go
  pkg/components/inspektor-gadget/component.go
  pkg/components/inspektor-gadget/component_test.go
  pkg/components/istio-operator/component.go
  pkg/components/istio-operator/component_test.go
  pkg/components/linkerd/component.go
  pkg/components/metallb/component.go
  pkg/components/metallb/component_test.go
  pkg/components/metrics-server/component.go
  pkg/components/metrics-server/component_test.go
  pkg/components/openebs-operator/component.go
  pkg/components/openebs-storage-class/component.go
  pkg/components/openebs-storage-class/component_test.go
  pkg/components/prometheus-operator/component.go
  pkg/components/prometheus-operator/component_test.go
  pkg/components/rook-ceph/component.go
  pkg/components/rook-ceph/component_test.go
  pkg/components/rook/component.go
  pkg/components/rook/component_conversion_test.go
  pkg/components/velero/azure/azure.go
  pkg/components/velero/component.go
  pkg/components/velero/component_test.go
  pkg/components/web-ui/component.go
  pkg/components/web-ui/component_test.go
  pkg/platform/aks/aks.go
  pkg/platform/aws/aws.go
  pkg/platform/baremetal/baremetal.go
  pkg/platform/packet/packet.go
  pkg/platform/platform.go
  pkg/platform/tinkerbell/tinkerbell.go
  test/components/component_delete_multiple_release_test.go
  test/components/install_test.go
Labels: priority/P3
